spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/ucenter?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.gt.project.model.entity
  mapper-locations: classpath*:/mapper/*.xml

servlet:
  multipart:
    # 上传文件总的最大值
    max-request-size: 100MB
    # 单个文件的最大值
    max-file-size: 100MB

log:
  path: ../logs

